#!/bin/bash
set -e

#  -f  Force removal of listener socket.
/usr/sbin/shibd -f
# Apache gets grumpy about PID and other (shm, cf AH01762 & AH01760) files pre-existing
rm -rf /usr/local/apache2/logs/httpd.pid /run/httpd/*

httpd && tail -F /var/log/shibboleth/shibd.log
