#!/bin/bash
set -e

#  -f  Force removal of listener socket.
/usr/sbin/shibd -f
# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid /run/httpd/httpd.pid

httpd && tail -F /var/log/shibboleth/shibd.log
